=== muhammetcnli/Hypertext-Hypermedia/xml/hobby_philosophy.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:simpleType name="shortString">
    <xs:restriction base="xs:string">
      <xs:minLength value="1"/>
      <xs:maxLength value="100"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="yearType">
    <xs:restriction base="xs:integer">
      <xs:minInclusive value="0"/>
      <xs:maxInclusive value="3000"/>
    </xs:restriction>
  </xs:simpleType>

  <!-- Added enumerated level type -->
  <xs:simpleType name="levelType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="beginner"/>
      <xs:enumeration value="intermediate"/>
      <xs:enumeration value="advanced"/>
    </xs:restriction>
  </xs:simpleType>

  <!-- Participation enumeration -->
  <xs:simpleType name="participationType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="online"/>
      <xs:enumeration value="offline"/>
      <xs:enumeration value="hybrid"/>
    </xs:restriction>
  </xs:simpleType>

  <!-- List of participation modes, restricted length -->
  <xs:simpleType name="participationModesType">
    <xs:restriction>
      <xs:simpleType>
        <xs:list itemType="participationType"/>
      </xs:simpleType>
      <xs:minLength value="1"/>
      <xs:maxLength value="3"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="ratingType">
    <xs:restriction base="xs:integer">
      <xs:minInclusive value="1"/>
      <xs:maxInclusive value="10"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="tagList">
    <xs:list itemType="xs:string"/>
  </xs:simpleType>

  <xs:simpleType name="langType">
    <xs:restriction base="xs:string">
      <xs:pattern value="[a-z]{2}"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="roleUnion">
    <xs:union memberTypes="xs:string ratingType"/>
  </xs:simpleType>

  <xs:attribute name="globalAttr" type="xs:string"/>

  <xs:complexType name="personalType">
    <xs:sequence>
      <xs:element name="name" type="shortString"/>
      <xs:element name="age" type="xs:integer"/>
      <xs:element name="location" type="locationType"/>
    </xs:sequence>
    <xs:attribute name="id" type="xs:ID" use="required"/>
    <xs:attribute ref="globalAttr" use="optional"/>
    <xs:attribute name="lang" type="langType"/>
  </xs:complexType>

  <xs:complexType name="locationType">
    <xs:all>
      <xs:element name="latitude" type="xs:decimal" minOccurs="0"/>
      <xs:element name="longitude" type="xs:decimal" minOccurs="0"/>
    </xs:all>
    <xs:attribute name="country" type="shortString"/>
    <xs:attribute name="city" type="shortString"/>
  </xs:complexType>

  <xs:complexType name="readingType">
    <xs:sequence>
      <xs:element name="title" type="shortString"/>
      <xs:element name="author" type="shortString"/>
      <xs:element name="year" type="yearType"/>
      <xs:element name="link" type="xs:anyURI"/>
    </xs:sequence>
    <xs:attribute name="id" type="xs:ID" use="optional"/>
  </xs:complexType>

  <xs:complexType name="branchType">
    <xs:sequence>
      <xs:element name="description" type="shortString"/>
      <xs:element name="readingList" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="reading" type="readingType" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="type" type="shortString" use="required"/>
    <xs:attribute name="level" type="levelType"/>
  </xs:complexType>

  <xs:group name="eventGroup">
    <xs:sequence>
      <xs:element name="title" type="shortString"/>
      <xs:element name="location" type="shortString"/>
    </xs:sequence>
  </xs:group>

  <xs:complexType name="eventType">
    <xs:sequence>
      <xs:group ref="eventGroup"/>
      <xs:element name="participants" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="participant" maxOccurs="unbounded">
              <xs:complexType>
                <xs:attribute name="idref" type="xs:IDREF"/>
                <xs:attribute name="role" type="roleUnion" use="optional"/>
              </xs:complexType>
            </xs:element>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="id" type="xs:ID" use="required"/>
    <xs:attribute name="type" type="xs:string" use="required"/>
    <xs:attribute name="date" type="xs:date"/>
  </xs:complexType>

  <xs:complexType name="photoType">
    <xs:sequence>
      <xs:element name="caption" type="shortString" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute name="id" type="xs:ID" use="required"/>
    <xs:attribute name="filename" type="xs:string" use="required"/>
  </xs:complexType>

  <xs:complexType name="galleryType">
    <xs:choice maxOccurs="unbounded">
      <xs:element name="photo" type="photoType"/>
      <xs:element name="sketch" type="photoType"/>
    </xs:choice>
  </xs:complexType>

  <xs:complexType name="linkType">
    <xs:simpleContent>
      <xs:extension base="xs:anyURI">
        <xs:attribute name="url" type="xs:anyURI" use="required"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <!-- Mixed content philosophy text -->
  <xs:complexType name="philosophyTextType" mixed="true">
    <xs:choice minOccurs="0" maxOccurs="unbounded">
      <xs:element name="em" type="shortString"/>
      <xs:element name="strong" type="shortString"/>
    </xs:choice>
  </xs:complexType>

  <xs:complexType name="philosophyOverviewType">
    <xs:sequence>
      <xs:element name="philosophyText" type="philosophyTextType" minOccurs="0"/>
      <xs:element name="branches">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="branch" type="branchType" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="events">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="event" type="eventType" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="gallery" type="galleryType"/>
      <xs:element name="externalLinks" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="link" type="linkType" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element ref="data" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute name="summary" type="xs:string"/>
    <xs:attribute name="focus" type="xs:string"/>
    <xs:attribute ref="globalAttr" use="optional"/>
  </xs:complexType>

  <xs:complexType name="weeklyPlanType">
    <xs:sequence>
      <xs:element name="day" maxOccurs="7" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="activity" maxOccurs="unbounded">
              <xs:complexType>
                <xs:attribute name="name" type="shortString" use="required"/>
                <xs:attribute name="durationHours" type="xs:decimal"/>
              </xs:complexType>
            </xs:element>
          </xs:sequence>
          <xs:attribute name="name" type="shortString" use="required"/>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="modes" type="participationModesType" use="optional"/>
    <xs:attribute ref="globalAttr" use="optional"/>
  </xs:complexType>

  <xs:element name="hobbyProfile">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="personal" type="personalType"/>
        <xs:element name="philosophyOverview" type="philosophyOverviewType"/>
        <xs:element name="weeklyPlan" type="weeklyPlanType"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="data" type="shortString"/>

  <xs:attribute name="shared" type="xs:boolean" default="false"/>

</xs:schema>

=== muhammetcnli/Hypertext-Hypermedia/xml/hobby_philosophy.xml
<?xml version="1.0" encoding="UTF-8"?>
<hobbyProfile xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="hobby_philosophy.xsd">
  <personal id="p001" lang="en" globalAttr="profile">
    <name>Muhammet Canlı</name>
    <age>20</age>
    <location country="Poland" city="Gdańsk" />
  </personal>
  <philosophyOverview summary="Personal reading and reflection" focus="ethics" globalAttr="overview">
    <philosophyText>This profile documents my evolving exploration of ethics and existential questions, combining <em>classic works</em> and <strong>modern reflections</strong>.</philosophyText>
    <branches>
      <branch type="ethics" level="intermediate">
        <description>Exploring moral theories</description>
        <readingList>
          <reading id="r1">
            <title>Nicomachean Ethics</title>
            <author>Aristotle</author>
            <year>350</year>
            <link>https://plato.stanford.edu/entries/aristotle-ethics/</link>
          </reading>
          <reading id="r2">
            <title>Being and Time</title>
            <author>Martin Heidegger</author>
            <year>1927</year>
            <link>https://plato.stanford.edu/entries/heidegger/</link>
          </reading>
        </readingList>
      </branch>
      <branch type="existentialism" level="beginner">
        <description>Existential questions and essays</description>
      </branch>
      <branch type="logic" level="beginner">
        <description>Basic logical structures</description>
      </branch>
    </branches>
    <events>
      <event id="e01" type="discussion" date="2025-03-15">
        <title>Local discussion group</title>
        <location>University cafe</location>
        <participants>
          <participant idref="p001" role="moderator"/>
          <participant idref="p002" role="5"/>
        </participants>
      </event>
      <event id="e02" type="reading" date="2024-12-10">
        <title>Reading workshop</title>
        <location>Online</location>
      </event>
    </events>
    <gallery>
      <photo id="ph1" filename="images/photo1.jpg"><caption>Reading corner</caption></photo>
      <photo id="ph2" filename="images/photo2.jpg"><caption>Notes</caption></photo>
      <photo id="ph3" filename="images/photo3.jpg"><caption>Discussion</caption></photo>
      <photo id="ph4" filename="images/photo4.jpg"><caption>Study desk</caption></photo>
      <photo id="ph5" filename="images/photo5.jpg"><caption>Book stack</caption></photo>
      <sketch id="sk1" filename="images/sketch1.jpg"><caption>Quick sketch</caption></sketch>
    </gallery>
    <externalLinks>
      <link url="https://plato.stanford.edu/">https://plato.stanford.edu/</link>
      <link url="https://iep.utm.edu/">https://iep.utm.edu/</link>
      <link url="https://www.philosophybasics.com/">https://www.philosophybasics.com/</link>
      <link url="https://www.khanacademy.org/humanities/philosophy">https://www.khanacademy.org/humanities/philosophy</link>
    </externalLinks>
    <data>Philosophy Hobby Data</data>
  </philosophyOverview>
  <weeklyPlan globalAttr="schedule" modes="online offline">
    <day name="Monday">
      <activity name="Reading" durationHours="1"/>
    </day>
    <day name="Wednesday">
      <activity name="Discussion" durationHours="2"/>
    </day>
    <day name="Saturday">
      <activity name="Writing" durationHours="1.5"/>
    </day>
  </weeklyPlan>
</hobbyProfile>
